### ISSUE TITLE
Consistens "is" prefix for booleans

### ISSUE THREAD

**Issue by manniL** [logaretm/vue-adaptive-utils#2]
Hey 👋 

First of all, thanks for the library ☺️ 

One thing that I noticed when checking out the README is that booleans are often prefixed with an "is" (e.g. `isOnline`) which is a great way to have readable flags/booleans. Unfortunately, the `unsupported` flag does *not* have that prefix.
Would it be worth to change that before the v1 to keep it consistent? 😋 

WDYT?

```js
import { useNetworkStatus } from 'vue-adaptive-utils';

const {
  isOnline,
  saveData,
  offlineAt,
  downlink,
  downlinkMax,
  effectiveConnectionType,
  networkType,
  unsupported
} = useNetworkStatus();
```

**Comment by logaretm** [comment]
Definitely, There are a bunch of Booleans that will need renaming, will
work on it.
